[project]
name = "recommender-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maxhall", email = "maxhall@kth.se" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
